module Tk
  require 'ffi-tk/command/choose_color'
  require 'ffi-tk/command/choose_directory'
  require 'ffi-tk/command/dialog'
  require 'ffi-tk/command/event'
  require 'ffi-tk/command/get_open_file'
  require 'ffi-tk/command/get_save_file'
  require 'ffi-tk/command/message_box'
  require 'ffi-tk/command/option_menu'
  require 'ffi-tk/command/popup'
  require 'ffi-tk/command/set_palette'
  require 'ffi-tk/command/vars'

  autoload :After,     'ffi-tk/command/after'
  autoload :Bell,      'ffi-tk/command/bell'
  autoload :Bind,      'ffi-tk/command/bind'
  autoload :BindTag,   'ffi-tk/command/bindtags'
  autoload :Bindtags,  'ffi-tk/command/bindtags'
  autoload :Cget,      'ffi-tk/command/cget'
  autoload :Clipboard, 'ffi-tk/command/clipboard'
  autoload :Configure, 'ffi-tk/command/configure'
  autoload :Destroy,   'ffi-tk/command/destroy'
  autoload :Focus,     'ffi-tk/command/focus'
  autoload :Font,      'ffi-tk/command/font'
  autoload :Grab,      'ffi-tk/command/grab'
  autoload :Grid,      'ffi-tk/command/grid'
  autoload :Grid,      'ffi-tk/command/grid'
  autoload :Image,     'ffi-tk/command/image'
  autoload :Lower,     'ffi-tk/command/lower'
  autoload :Pack,      'ffi-tk/command/pack'
  autoload :Place,     'ffi-tk/command/place'
  autoload :Raise,     'ffi-tk/command/raise'
  autoload :Selection, 'ffi-tk/command/selection'
  autoload :TkCmd,     'ffi-tk/command/tk_cmd'
  autoload :WM,        'ffi-tk/command/wm'
  autoload :Wait,      'ffi-tk/command/wait'
  autoload :Winfo,     'ffi-tk/command/winfo'
  autoload :Scrollable,'ffi-tk/command/scrollable'
end
